### ISSUE TITLE
Support for using CDN as the asset host

### ISSUE THREAD

**Issue by tenshiAMD** [jamesmartin/inline_svg#127]
@jamesmartin Hi there, thank you for this great gem you've made, I was wondering how to use CDN as the asset host, may I know how the implementation for this? 

We are using Rails 6 and defined configuration for `asset_host` in the environment configuration (please see the example below):

```
config.action_controller.asset_host = "cdn.example.com"
```

For the view:

```
<%= inline_svg_tag "gold-bar.svg", style: 'fill: gold; width: 250px;' %>
```

**Comment by jamesmartin** [comment]
👋 @tenshiAMD thanks for opening this issue. You may be in uncharted waters here. I've personally never tried to use this gem with an external CDN asset host. 

Because the gem reads an SVG file, transforms it in memory and embeds the content into the rendered HTML page, you will lose the benefit of having the asset distributed via the CDN. 

Are you sure that's what you want? 🤔 If so…

The `inline_svg_tag` method will either use Sprockets/Asset Pipeline (in older versions of Rails), or use a [naive static asset finder](https://github.com/jamesmartin/inline_svg/blob/17ae73a8eb7ede3c914cdd2ecafa82a2db9293b7/lib/inline_svg.rb#L45-L48) to attempt to find SVG files based on the asset paths defined by Rails:

https://github.com/jamesmartin/inline_svg/blob/17ae73a8eb7ede3c914cdd2ecafa82a2db9293b7/lib/inline_svg/static_asset_finder.rb#L21-L25 

If the naive static asset finder is not working for you then it is possible to write your own one, which just needs to accept a filename argument and return a `Pathname` object, which implies reading the remote file from the CDN and making it available as an `IO` object such that it can be transformed by the rest of the gem:

```ruby

class MyCdnAssetFinder
    def find_asset(filename)
        # 1. look for filename on CDN
        # 2. read the file and store it somewhere (maybe using Tempfile)
        # 3. return the Pathname of the file so that it can be read as an IO object by the rest of the gem
    end
end

InlineSvg.configure do |config|
  config.asset_finder = MyCdnAssetFinder
end
```

Does that make sense? 🤔

**Comment by tenshiAMD** [comment]
@jamesmartin thanks for the clarification!
