### ISSUE TITLE
Set SVG height and width as an option

### ISSUE THREAD

**Issue by 2metres** [jamesmartin/inline_svg#4]

**Comment by jamesmartin** [comment]
Added in [version 0.4.0](https://github.com/jamesmartin/inline_svg/blob/master/CHANGELOG.md#040---2015-03-22).

Use the `size` option to [set width and height](https://github.com/jamesmartin/inline_svg/blob/master/README.md#options).

**Comment by pineapple-thief** [comment]
Maybe you could add rails-like syntax for dimensions like size: "12x16" ?

**Comment by jamesmartin** [comment]
@pineapple-thief thanks for the suggestion. My [first attempt at the Size transformation](https://github.com/jamesmartin/inline_svg/commit/03452ed037a59a39a14d966a6cc24a56041743ff#diff-5087a0c1014da75b9795feb78a7e4f8eR12) used the "5x5" notation, inspired by the [Rails `image_tag`](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-image_tag)  helper syntax. This is fine for HTML img tags because the [HTML specification](http://www.w3.org/TR/html-markup/img.html#img.attrs.height) assumes height and width attributes are always supplied as CSS pixels.

However, the notation is more complicated for SVG because the [specification requires height and width units to be specified as a `length` type](http://www.w3.org/TR/SVG/types.html#DataTypeLength), which could be something like "px" or "em" or "%". I chose the `*` — multiplication — delimiter, which doesn't appear in any of the SVG `length` units.

For example, imagine this hypothetical scenario: `inline_svg('some.svg', size: '12pxx16px')`. This is pretty hard to read as a human. I find it much easier to read this: `inline_svg('some.svg', size: '12px*16px')`. 

What do you think?

**Comment by pineapple-thief** [comment]
Oh, it makes sense now, right. But what about id and data options? Those
could be helpful.

2015-03-26 8:55 GMT+10:00 James Martin <notifications@github.com>:

**Comment by 2metres** [comment]
Maybe setting an explicit height and width would be nice like `inline_svg('some.svg', width: '100%', height: 'auto')`

**Comment by pineapple-thief** [comment]
Yeah, I second this, for some width/height options would be more readable than size, so nice to have choice here.

**Comment by jamesmartin** [comment]
OK, will do this as a [separate issue](https://github.com/jamesmartin/inline_svg/issues/11).

**Comment by jamesmartin** [comment]
Added separate `height` and `width` options in [v0.5.0](https://github.com/jamesmartin/inline_svg/blob/master/CHANGELOG.md#050---2015-03-29).
