### ISSUE TITLE
Feature request: Support for helper tag in haml-coffee templates

### ISSUE THREAD

**Issue by mfrejnik** [jamesmartin/inline_svg#58]
How complicated it would be to apply the support for the great inline-svg helper tag in `haml_coffee_assets` JST templates?

**Comment by jamesmartin** [comment]
@mfrejnik thanks for the feature request. I'm not familiar with haml-coffee, or its inline-svg helper tag. Could you point me towards some documentation?

To set expectations I'd say that regardless of how easy it is to support haml-coffee inline-svg it's unlikely that I would add this to the core of `inline_svg`. In order to solve a smaller set of problems for a wider audience I try to limit the core functionality of the library, which also helps with maintenance.

You might be able to integrate haml-coffee inline-svg by writing a [custom transformation](https://github.com/jamesmartin/inline_svg#custom-transformations), and I'd be happy to help you with that if it would solve your specific problem.

**Comment by jamesmartin** [comment]
Closing this for now. @mfrejnik if you have further questions or need help with a transformation feel free to let me know.
