### ISSUE TITLE
Undefined method `find_asset`

### ISSUE THREAD

**Issue by GuillaumeWrobel** [jamesmartin/inline_svg#97]
Hello,

Just upgraded gem from 1.4.0 to 1.5.0 and this error came in production. Nothing changed on my side:

**html**
```html
<div>
  <%= inline_svg("logo.svg") %>
</div>
```

**error**
```
ActionView::Template::Error undefined method `find_asset` for nil:NilClass
```

Probably linked to the webpack code.

Happy to help if you need more info.

**Comment by organicweb** [comment]
Same problem here, no update but error message : 

**HTML :** 
```
- cache 'main--nav-socials' do
  = link_to root_path, class: %w(navbar-brand) do
    %span.sr-only Lorem ipsum
    = inline_svg 'logo.svg', height: '30px'
```

**Error :** 

`ActionView::Template::Error (undefined method `find_asset' for nil:NilClass):`

**Comment by bjeanes** [comment]
Same problem. It looks like adding Webpacker support may have implicitly broken the gem for people who do not have webpacker installed.

**Comment by jamesmartin** [comment]
@GuillaumeWrobel thanks for opening this issue and sorry about the error. Could you tell me:

- Which version of Rails are you using?
- Are you using Webpack at all?
- Are you using Sprockets or Webpacker? Or both?

You mentioned that you're seeing this in production. Is it reproducible in development also?

(P.S. anybody else on this thread experiencing this problem, please feel free to also answer these questions)

> Same problem. It looks like adding Webpacker support may have implicitly broken the gem for people who do not have webpacker installed.

When Webpacker is not installed the gem _should_ try to use Sprockets by default and fallback to the naive `StaticAssetFinder` if that can't be found.

**Comment by bgmat** [comment]
The same error for me too.
Using rails 5.2.3 on heroku (no webpack, no custom asset_finder).
I downgraded to version 1.4.0

**Comment by jamesmartin** [comment]
Thanks for the information, @bgmat. I was able to reproduce this on a test Heroku app. I've shipped a fixed version that falls back to the static asset finder (4c0da9ecc56e3) in [v1.5.1](https://github.com/jamesmartin/inline_svg/releases/tag/v1.5.1). Please give it a try and let me know if it doesn't fix the problem for you.

Sorry for the trouble, everybody. The gem has decent test coverage, but the failure in this case was (of course) in the one untested part: The Railtie. This has remained largely untested because it's kind of painful to test a Railtie in a gem (all the Rails dependencies). I've started looking into lightweight ways to unit test Railties without requiring all of Rails so I can hopefully prevent this class of problem in future.

**Comment by GuillaumeWrobel** [comment]
same config as @bgmat 

Rails 5.2.3 on Heroku
No webpack
No custom `asset_finder`
No `InlineSvg` config

**Comment by jamesmartin** [comment]
@GuillaumeWrobel thanks for the info. Please try `bundle update inline_svg` and give v1.5.1 a try. I think that _should_ fix your problem. If not, please let me know.

**Comment by GuillaumeWrobel** [comment]
`1.5.1` version works! Thank you for the quick answer & fix @jamesmartin

**Comment by organicweb** [comment]
Sorry for late response

No webpack
Rails 4.2.11.1
Ruby 2.5.5 or Ruby 2.5.0
No custom asset_finder
No InlineSvg config

I'll give a try this week to 1.5.1
